# frozen_string_literal: true

# Homebrew formula for agent-manager (am).
# This checked-in copy is regenerated by .github/workflows/release.yml on every
# tagged release (which also fills in the am-acp-shell resource sha256 values).
class Am < Formula
  desc "Control plane for AI agents: catalog, MCP gateway, ACP/A2A router"
  homepage "https://github.com/Codeseys-Labs/agent-manager"
  version "0.5.0-rc6"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Codeseys-Labs/agent-manager/releases/download/v#{version}/am-darwin-arm64"
      sha256 "07d545194a53f3f93348dbd9dc1e9abc0ea97b2f1026fab6f327ee5f80bf9ddd"
      resource "am-acp-shell" do
        url "https://github.com/Codeseys-Labs/agent-manager/releases/download/v#{version}/am-acp-shell-darwin-arm64"
      end
    end
    on_intel do
      url "https://github.com/Codeseys-Labs/agent-manager/releases/download/v#{version}/am-darwin-x64"
      sha256 "a8e2ff751840bd590c9d239d3f31787143210da85f313337ee15040abcf0184a"
      resource "am-acp-shell" do
        url "https://github.com/Codeseys-Labs/agent-manager/releases/download/v#{version}/am-acp-shell-darwin-x64"
      end
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Codeseys-Labs/agent-manager/releases/download/v#{version}/am-linux-arm64"
      sha256 "a0bb1e03b3801898e01a6dd8cc34affdcfd830933c9dfa83b53702b4ff280416"
      resource "am-acp-shell" do
        url "https://github.com/Codeseys-Labs/agent-manager/releases/download/v#{version}/am-acp-shell-linux-arm64"
      end
    end
    on_intel do
      url "https://github.com/Codeseys-Labs/agent-manager/releases/download/v#{version}/am-linux-x64"
      sha256 "8917787506c35d9025ebc500b9c311f688ba9bbf581bc913872e4bd2e709bd10"
      resource "am-acp-shell" do
        url "https://github.com/Codeseys-Labs/agent-manager/releases/download/v#{version}/am-acp-shell-linux-x64"
      end
    end
  end

  def install
    # Primary binary: install the downloaded artifact as `am`.
    binary_name = stable.url.split("/").last
    bin.install binary_name => "am"

    # Tier-2 shim binary (ADR-0033): `am-acp-shell` is the wrapper that
    # `am run <shim>` spawns after `am agent enable-shim <name>`. Without it,
    # Tier-2 shims fail at runtime with `am-acp-shell: command not found`.
    # Install it whenever the resource is present for this platform.
    shell_resource = resources.find { |r| r.name == "am-acp-shell" }
    return if shell_resource.nil?

    shell_resource.stage do
      shell_binary = Dir["am-acp-shell-*"].first
      bin.install shell_binary => "am-acp-shell" if shell_binary
    end
  end

  def caveats
    <<~EOS
      To get started:
        am init

      Then sync your config:
        am apply

      To use a Tier-2 wrapped agent (aider / amazon-q / cody):
        am agent enable-shim <name> --yes
      Tier-2 wrappers inherit the underlying CLI's trust posture.
      See ADR-0033 for the security caveat.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/am version")
  end
end
